version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Mapping du port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"  # Changez ce port si nécessaire
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
